# Generated by Django 6.0.3 on 2026-03-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_created_at_lesson_pdf_lessonattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_final_passing_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
